---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ADDR_RANGE: 192.168.2.40-192.168.2.199
  VPN_PORT: "51820"
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "59494"
  VPN_COUNTRY: CA
  NETWORK_K8S_CLUSTER_CIDR: "11.42.0.0/16"
  NETWORK_K8S_SERVICE_CIDR: "11.43.0.0/16"
  NETWORK_MANAGEMENT_CIDR: "192.168.0.0/16"
  NETWORK_SERVER_CIDR: "192.168.0.0/16"
  NETWORK_GUEST_CIDR: "192.168.0.0/16"
  GATEWAY_ADDR: 192.168.1.1
  SVC_INGRESS_ADDR: "192.168.2.40"
  SVC_BLOCKY_ADDR: "192.168.2.88"
  SVC_MARIADB_ADDR: "192.168.2.89"
  SVC_VAULT_ADDR: "192.168.2.90"
  SVC_CONSUL_ADDR: "192.168.2.91"
  SVC_MOSQUITTO_ADDR: "192.168.2.92"
  SVC_HASS_ADDR: "192.168.2.93"
  SVC_LOKI_ADDR: "192.168.2.94"
  VALHEIM_SVC_IP2: "192.168.2.95"
  MC_SURV_ADDR: "192.168.2.96"
  VALHEIM_SVC_IP: "192.168.2.97"
  SVC_SYSLOG_ADDR: "192.168.2.98"
  PLEX_LB: "192.168.2.99"
  NAS1_ADDR: 192.168.1.177
  NAS2_ADDR: 192.168.1.200
  NAS3_ADDR: 192.168.1.207
  NFS_BACKUP: "nfs://192.168.1.200:/volume1/kube2"
