---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prowlarr
  # - bazarr
  # - calibre
  # - calibre-web
  - tautulli
 # - ombi
  - plex
  # - sabnzbd
  # - sonarr
  # - radarr
  # - radarr-uhd
  # - overseerr
  # - readarr
